# Generated by Django 5.0.4 on 2024-05-01 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField(null=True, verbose_name='fecha de nacimiento')),
                ('telefono', models.PositiveIntegerField(unique=True)),
                ('correo', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('usuario', models.CharField(max_length=200)),
                ('contraseña', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Psicologa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField(null=True, verbose_name='fecha de nacimiento')),
                ('telefono', models.PositiveIntegerField(unique=True)),
                ('correo', models.CharField(max_length=200)),
                ('usuario', models.CharField(max_length=200)),
                ('contraseña', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField(null=True, verbose_name='fecha de nacimiento')),
                ('telefono', models.PositiveIntegerField(unique=True)),
                ('correo', models.CharField(max_length=200)),
                ('usuario', models.CharField(max_length=200)),
                ('contraseña', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('psicologa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psicologas', to='Comunidad.psicologa')),
                ('usuario', models.ManyToManyField(to='Comunidad.usuario')),
            ],
        ),
    ]
